//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proview.CodeChallenge.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInput
    {
        public int Id { get; set; }
        public string Expression { get; set; }
        public string Result { get; set; }
    }
}
